dist: trusty
sudo: true
language: python3
before_install:
- sudo apt-get -qq update
install:
- true
script:
- true
branches:
  only:
  - master
deploy:
  provider: s3
  access_key_id: AKIAJM674IB6P6KCRS6A
  secret_access_key:
    secure: eHe+YpVeWuGOOo8rYSe77y8ueuXuqBAaJOyTouRQz9N0Ujk7sWo4tEAdhKX73zz5kOAPjEbGI/Qni7Xcy32sDhUw2dye3CWjBYUQogQp3TTfzBlU7z09edL8yE/AVo/arXBbPsfTRwAX77LTPM1YSj2h8RWw1oT5T2lr+KYuI7ovb0+E/ZdtE2x5gRQbYnUVwmUdi1RalT7zvzBk1K/tH2Lz55hiM+ei10QCy3/cnLgc5F4q1Wsk9kJyfQex4NGOeDW6S31gQHnjsvhFtJJqby0BEqZTgh93i+OwBM5yP1cpEFEHlsO64uyE32iXhXM+mFibhNbCsdwckYB7qdabXofwpSK3Jwgue1Qi8ZJqKZg2IQGjkhUrc5igGCFLlxIX0Xrk+0qsNjqWjwJCWf9F35UThUaooGjjaQgCTGUFf8xjVanx1JdFmYRLM6siZxAprn0wynlPkYEvSIlx1PFvT5i9XRTuYjwETMrfB+Rf0YQLC/pufYP84oeak9zQO96Pr9othwcDXgCVKrDMZaD0bnHPCejdSs3WhTDf22L+zhc4bUM0tu/qnVZ34JtUD7SyJMjPvf9ogrQMKCg35QCDgPgQMmK2txI8cY+BGZcB7TJj4rzVWZ9lP3+5qkDG95e2QZn0gnOYVhSmZ3WZ4W9CpkY9xGmBZ5FpBOWTcuIo+Zk=
  bucket: key.fileformat.info
  local-dir: www
  skip_cleanup: true
  on:
    repo: fileformat/rosetta-key
    branch: master
